# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0de28dc22e28bcb6ee350136254a3d34f889b91e6d3cd46b423ae510bf826909c6f74dc07ff2aa91b478c2f38f3c7d40b426ca89ad9acd46ec2b5e1b91d6c458

test:
  secret_key_base: 5038be30dd0a03b2a26e2292b5e9622e203cc0774873dc4a68d884654650c81c996291cea109e06d3ab1c3cc8c527059271f6c2bae23381c0c8f90124582f79c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
